# Generated by Django 5.2.14 on 2026-05-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RessourcePedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type_ressource', models.CharField(default='cours', max_length=20)),
                ('module', models.CharField(max_length=150)),
                ('niveau', models.CharField(default='L3', max_length=10)),
                ('annee_scolaire', models.CharField(default='2024-2025', max_length=9)),
                ('fichier', models.FileField(upload_to='ressources/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
