# Generated by Django 5.2.14 on 2026-05-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=150)),
                ('type_note', models.CharField(default='examen', max_length=20)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=4)),
                ('coefficient', models.PositiveSmallIntegerField(default=4)),
                ('date_publication', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
    ]
