# Generated by Django 5.2 on 2026-05-28 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=100)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('semestre', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['intitule'],
            },
        ),
        migrations.AlterField(
            model_name='note',
            name='coefficient',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='note',
            name='publie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_publiees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='type_note',
            field=models.CharField(choices=[('examen', 'Examen'), ('tp', 'TP'), ('td', 'TD'), ('controle', 'Contrôle')], default='examen', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.module'),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('etudiant', 'module', 'type_note')},
        ),
    ]
