# Generated by Django 6.0.5 on 2026-05-23 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_attestation",
                    models.CharField(
                        choices=[
                            ("scolarite", "Attestation de scolarité"),
                            ("reussite", "Attestation de réussite"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_generation", models.DateField(auto_now_add=True)),
                ("fichier", models.FileField(upload_to="attestations/")),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attestations_generees",
                        to="api.admin",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attestations",
                        to="api.etudiant",
                    ),
                ),
            ],
        ),
    ]
