# Generated by Django 6.0.5 on 2026-05-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_attestation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attestation",
        ),
    ]
