# Generated by Django 6.0.5 on 2026-05-23 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_delete_attestation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_attestation",
                    models.CharField(
                        choices=[
                            ("scolarite", "Attestation de scolarité"),
                            ("inscription", "Attestation d’inscription"),
                            ("reussite", "Attestation de réussite"),
                        ],
                        max_length=50,
                    ),
                ),
                ("annee_academique", models.CharField(max_length=20)),
                ("fichier", models.FileField(upload_to="attestations/")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attestations",
                        to="api.etudiant",
                    ),
                ),
            ],
        ),
    ]
