# Generated by Django 6.0.5 on 2026-05-24 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_delete_attestation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_attestation",
                    models.CharField(
                        choices=[("inscription", "Attestation inscription")],
                        max_length=50,
                    ),
                ),
                ("fichier", models.FileField(upload_to="attestations/")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attestations",
                        to="api.etudiant",
                    ),
                ),
            ],
        ),
    ]
