# Generated by Django 5.2 on 2026-05-29 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_attestation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attestation",
            options={"ordering": ["-date_creation"]},
        ),
        migrations.AlterModelOptions(
            name="ressourcepedagogique",
            options={},
        ),
        migrations.AlterField(
            model_name="attestation",
            name="etudiant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attestations",
                to="api.demandeinscription",
            ),
        ),
    ]
